import { Client, Appointment, Business, Location, Service } from '@/types'

export const demoBusiness: Business = {
  id: 'demo-business',
  name: 'Clínica Dental Sonrisas',
  description: 'Clínica dental profesional con servicios integrales',
  category: 'Salud',
  logo_url: '',
  website: 'https://clinicasonrisas.com',
  phone: '+1 (555) 000-0000',
  email: 'info@clinicasonrisas.com',
  address: 'Calle Principal 123',
  city: 'Madrid',
  state: 'Madrid',
  country: 'España',
  postal_code: '28001',
  latitude: 40.4168,
  longitude: -3.7038,
  business_hours: {
    monday: { open: '08:00', close: '17:00', closed: false },
    tuesday: { open: '08:00', close: '17:00', closed: false },
    wednesday: { open: '08:00', close: '17:00', closed: false },
    thursday: { open: '08:00', close: '17:00', closed: false },
    friday: { open: '08:00', close: '17:00', closed: false },
    saturday: { open: '09:00', close: '13:00', closed: false },
    sunday: { open: '00:00', close: '00:00', closed: true }
  },
  timezone: 'Europe/Madrid',
  owner_id: 'demo-user',
  settings: {
  appointment_buffer: 15,
  advance_booking_days: 30,
  cancellation_policy: 24,
  auto_confirm: true,
  require_deposit: false,
  deposit_percentage: 0,
  currency: 'EUR'
  },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  is_active: true
}

export const demoLocations: Location[] = [
  {
    id: 'demo-location-1',
    business_id: 'demo-business',
    name: 'Sede Principal - Centro',
    address: 'Calle Principal 123',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    postal_code: '28001',
    latitude: 40.4168,
    longitude: -3.7038,
    phone: '+1 (555) 000-0000',
    email: 'centro@clinicasonrisas.com',
    business_hours: {
      monday: { open: '08:00', close: '17:00', is_open: true },
      tuesday: { open: '08:00', close: '17:00', is_open: true },
      wednesday: { open: '08:00', close: '17:00', is_open: true },
      thursday: { open: '08:00', close: '17:00', is_open: true },
      friday: { open: '08:00', close: '17:00', is_open: true },
      saturday: { open: '09:00', close: '13:00', is_open: true },
      sunday: { open: '00:00', close: '00:00', is_open: false }
    },
  is_active: true,
  is_main: true,
    created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: 'demo-user'
  },
  {
    id: 'demo-location-2',
    business_id: 'demo-business',
    name: 'Sede Norte',
    address: 'Avenida Norte 456',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    postal_code: '28002',
    latitude: 40.4500,
    longitude: -3.6900,
    phone: '+1 (555) 000-0001',
    email: 'norte@clinicasonrisas.com',
    business_hours: {
      monday: { open: '09:00', close: '18:00', is_open: true },
      tuesday: { open: '09:00', close: '18:00', is_open: true },
      wednesday: { open: '09:00', close: '18:00', is_open: true },
      thursday: { open: '09:00', close: '18:00', is_open: true },
      friday: { open: '09:00', close: '18:00', is_open: true },
      saturday: { open: '10:00', close: '14:00', is_open: true },
      sunday: { open: '00:00', close: '00:00', is_open: false }
    },
  is_active: true,
  is_main: false,
    created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: 'demo-user'
  }
]

export const demoServices: Service[] = [
  {
    id: 'demo-service-1',
    business_id: 'demo-business',
    name: 'Limpieza Dental',
    description: 'Limpieza dental profunda y pulido',
    duration: 60,
    price: 80,
    currency: 'EUR',
    category: 'Preventiva',
  is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: 'demo-user'
  },
  {
    id: 'demo-service-2',
    business_id: 'demo-business',
    name: 'Empaste',
    description: 'Empaste dental con composite',
    duration: 90,
    price: 120,
    currency: 'EUR',
    category: 'Restaurativa',
  is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: 'demo-user'
  },
  {
    id: 'demo-service-3',
    business_id: 'demo-business',
    name: 'Extracción',
    description: 'Extracción dental simple',
    duration: 45,
    price: 100,
    currency: 'EUR',
    category: 'Cirugía',
  is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: 'demo-user'
  },
  {
    id: 'demo-service-4',
    business_id: 'demo-business',
    name: 'Blanqueamiento',
    description: 'Blanqueamiento dental profesional',
    duration: 120,
    price: 200,
    currency: 'EUR',
    category: 'Estética',
  is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: 'demo-user'
  }
]

export const demoClients: Client[] = [
  {
    id: 'demo-client-1',
    business_id: 'demo-business',
    name: 'Ana García',
    email: 'ana.garcia@email.com',
    phone: '+1 (555) 123-4567',
    whatsapp: '+1 (555) 123-4567',
    company: 'Tech Solutions',
    address: 'Calle Luna 45',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    language: 'es',
    total_appointments: 8,
    last_appointment: '2024-12-01T10:00:00Z',
    is_recurring: true,
    status: 'active',
    tags: ['VIP', 'Frecuente'],
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
    created_by: 'demo-user'
  },
  {
    id: 'demo-client-2',
    business_id: 'demo-business',
    name: 'Carlos Rodríguez',
    email: 'carlos.rodriguez@email.com',
    phone: '+1 (555) 234-5678',
    whatsapp: '+1 (555) 234-5678',
    company: 'Marketing Pro',
    address: 'Avenida Sol 78',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    language: 'es',
    total_appointments: 5,
    last_appointment: '2024-11-15T14:00:00Z',
    is_recurring: true,
    status: 'active',
    tags: ['Regular'],
    created_at: '2024-01-16T11:30:00Z',
    updated_at: '2024-11-15T14:00:00Z',
    created_by: 'demo-user'
  },
  {
    id: 'demo-client-3',
    business_id: 'demo-business',
    name: 'María López',
    email: 'maria.lopez@email.com',
    phone: '+1 (555) 345-6789',
    whatsapp: '+1 (555) 345-6789',
    company: 'Design Studio',
    address: 'Plaza Mayor 12',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    language: 'es',
    total_appointments: 12,
    last_appointment: '2024-12-05T16:00:00Z',
    is_recurring: true,
    status: 'active',
    tags: ['VIP', 'Leal'],
    created_at: '2024-01-17T09:15:00Z',
    updated_at: '2024-12-05T16:00:00Z',
    created_by: 'demo-user'
  },
  {
    id: 'demo-client-4',
    business_id: 'demo-business',
    name: 'Juan Martínez',
    email: 'juan.martinez@email.com',
    phone: '+1 (555) 456-7890',
    whatsapp: '+1 (555) 456-7890',
    company: 'Consulting Group',
    address: 'Calle Mayor 89',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    language: 'es',
    total_appointments: 3,
    last_appointment: '2024-10-20T11:00:00Z',
    is_recurring: false,
  status: 'inactive',
    tags: ['Nuevo'],
    created_at: '2024-01-18T14:20:00Z',
    updated_at: '2024-10-20T11:00:00Z',
    created_by: 'demo-user'
  },
  {
    id: 'demo-client-5',
    business_id: 'demo-business',
    name: 'Laura Sánchez',
    email: 'laura.sanchez@email.com',
    phone: '+1 (555) 567-8901',
    whatsapp: '+1 (555) 567-8901',
    company: 'Finance Corp',
    address: 'Gran Vía 234',
    city: 'Madrid',
    state: 'Madrid',
    country: 'España',
    language: 'es',
    total_appointments: 15,
    last_appointment: '2024-12-10T09:00:00Z',
    is_recurring: true,
    status: 'active',
    tags: ['VIP', 'Ejecutiva'],
    created_at: '2024-01-19T16:45:00Z',
    updated_at: '2024-12-10T09:00:00Z',
    created_by: 'demo-user'
  }
]

// Generate appointments for the next 30 days
export const demoAppointments: Appointment[] = [
  // Today's appointments
  {
    id: 'demo-apt-1',
    business_id: 'demo-business',
    location_id: 'demo-location-1',
    service_id: 'demo-service-1',
    user_id: 'demo-user',
    client_id: 'demo-client-1',
    title: 'Limpieza Dental',
    description: 'Limpieza dental profunda y revisión',
    client_name: 'Ana García',
    client_email: 'ana.garcia@email.com',
    client_phone: '+1 (555) 123-4567',
    client_whatsapp: '+1 (555) 123-4567',
    start_time: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 10, 0).toISOString(),
    end_time: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 11, 0).toISOString(),
    status: 'scheduled',
    location: 'Sede Principal - Centro',
    notes: 'Cliente frecuente, primera limpieza del año',
    price: 80,
    currency: 'EUR',
    reminder_sent: false,
    created_at: '2024-01-20T08:00:00Z',
    updated_at: '2024-01-20T08:00:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-1',
    clientName: 'Ana García',
    clientEmail: 'ana.garcia@email.com',
    clientPhone: '+1 (555) 123-4567',
    date: new Date().toISOString().split('T')[0],
    startTime: '10:00',
    time: '10:00',
    endTime: '11:00',
    userId: 'demo-user',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-01-20T08:00:00Z',
    priority: 'high',
    tags: ['VIP'],
    reminderSent: false
  },
  {
    id: 'demo-apt-2',
    business_id: 'demo-business',
    location_id: 'demo-location-1',
    service_id: 'demo-service-2',
    user_id: 'demo-user',
    client_id: 'demo-client-2',
    title: 'Empaste Dental',
    description: 'Empaste en molar superior derecho',
    client_name: 'Carlos Rodríguez',
    client_email: 'carlos.rodriguez@email.com',
    client_phone: '+1 (555) 234-5678',
    client_whatsapp: '+1 (555) 234-5678',
    start_time: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 14, 30).toISOString(),
    end_time: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 16, 0).toISOString(),
    status: 'scheduled',
    location: 'Sede Principal - Centro',
    notes: 'Paciente nervioso, usar anestesia adicional',
    price: 120,
    currency: 'EUR',
    reminder_sent: false,
    created_at: '2024-01-20T08:15:00Z',
    updated_at: '2024-01-20T08:15:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-2',
    clientName: 'Carlos Rodríguez',
    clientEmail: 'carlos.rodriguez@email.com',
    clientPhone: '+1 (555) 234-5678',
    date: new Date().toISOString().split('T')[0],
    startTime: '14:30',
    time: '14:30',
    endTime: '16:00',
    userId: 'demo-user',
    createdAt: '2024-01-20T08:15:00Z',
    updatedAt: '2024-01-20T08:15:00Z',
    priority: 'medium',
    tags: ['Empaste'],
    reminderSent: false
  },
  // Tomorrow's appointments
  {
    id: 'demo-apt-3',
    business_id: 'demo-business',
    location_id: 'demo-location-2',
    service_id: 'demo-service-4',
    user_id: 'demo-user',
    client_id: 'demo-client-3',
    title: 'Blanqueamiento Dental',
    description: 'Blanqueamiento dental profesional',
    client_name: 'María López',
    client_email: 'maria.lopez@email.com',
    client_phone: '+1 (555) 345-6789',
    client_whatsapp: '+1 (555) 345-6789',
    start_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T09:00:00.000Z'),
    end_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T11:00:00.000Z'),
    status: 'scheduled',
    location: 'Sede Norte',
    notes: 'Cliente VIP, procedimiento estético',
    price: 200,
    currency: 'EUR',
    reminder_sent: false,
    created_at: '2024-01-20T08:30:00Z',
    updated_at: '2024-01-20T08:30:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-3',
    clientName: 'María López',
    clientEmail: 'maria.lopez@email.com',
    clientPhone: '+1 (555) 345-6789',
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '09:00',
    time: '09:00',
    endTime: '11:00',
    userId: 'demo-user',
    createdAt: '2024-01-20T08:30:00Z',
    updatedAt: '2024-01-20T08:30:00Z',
    priority: 'high',
    tags: ['VIP', 'Estética'],
    reminderSent: false
  },
  {
    id: 'demo-apt-4',
    business_id: 'demo-business',
    location_id: 'demo-location-1',
    service_id: 'demo-service-1',
    user_id: 'demo-user',
    client_id: 'demo-client-5',
    title: 'Limpieza Dental',
    description: 'Limpieza dental de rutina',
    client_name: 'Laura Sánchez',
    client_email: 'laura.sanchez@email.com',
    client_phone: '+1 (555) 567-8901',
    client_whatsapp: '+1 (555) 567-8901',
    start_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T16:00:00.000Z'),
    end_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T17:00:00.000Z'),
    status: 'scheduled',
    location: 'Sede Principal - Centro',
    notes: 'Cliente ejecutiva, puntual siempre',
    price: 80,
    currency: 'EUR',
    reminder_sent: false,
    created_at: '2024-01-20T08:45:00Z',
    updated_at: '2024-01-20T08:45:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-5',
    clientName: 'Laura Sánchez',
    clientEmail: 'laura.sanchez@email.com',
    clientPhone: '+1 (555) 567-8901',
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '16:00',
    time: '16:00',
    endTime: '17:00',
    userId: 'demo-user',
    createdAt: '2024-01-20T08:45:00Z',
    updatedAt: '2024-01-20T08:45:00Z',
    priority: 'medium',
    tags: ['VIP', 'Ejecutiva'],
    reminderSent: false
  },
  // Day after tomorrow
  {
    id: 'demo-apt-5',
    business_id: 'demo-business',
    location_id: 'demo-location-1',
    service_id: 'demo-service-3',
    user_id: 'demo-user',
    client_id: 'demo-client-4',
    title: 'Extracción Dental',
    description: 'Extracción de muela del juicio',
    client_name: 'Juan Martínez',
    client_email: 'juan.martinez@email.com',
    client_phone: '+1 (555) 456-7890',
    client_whatsapp: '+1 (555) 456-7890',
    start_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T11:00:00.000Z'),
    end_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T11:45:00.000Z'),
    status: 'scheduled',
    location: 'Sede Principal - Centro',
    notes: 'Procedimiento quirúrgico, revisar historial',
    price: 100,
    currency: 'EUR',
    reminder_sent: false,
    created_at: '2024-01-20T09:00:00Z',
    updated_at: '2024-01-20T09:00:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-4',
    clientName: 'Juan Martínez',
    clientEmail: 'juan.martinez@email.com',
    clientPhone: '+1 (555) 456-7890',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '11:00',
    time: '11:00',
    endTime: '11:45',
    userId: 'demo-user',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-20T09:00:00Z',
    priority: 'high',
    tags: ['Cirugía'],
    reminderSent: false
  },
  // Completed appointments (last week)
  {
    id: 'demo-apt-7',
    business_id: 'demo-business',
    location_id: 'demo-location-1',
    service_id: 'demo-service-1',
    user_id: 'demo-user',
    client_id: 'demo-client-2',
    title: 'Primera Consulta',
    description: 'Consulta inicial y revisión',
    client_name: 'Carlos Rodríguez',
    client_email: 'carlos.rodriguez@email.com',
    client_phone: '+1 (555) 234-5678',
    client_whatsapp: '+1 (555) 234-5678',
    start_time: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T10:00:00.000Z'),
    end_time: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T11:30:00.000Z'),
    status: 'completed',
    location: 'Sede Principal - Centro',
    notes: 'Paciente nuevo, muy satisfecho con el servicio',
    price: 80,
    currency: 'EUR',
    reminder_sent: true,
    created_at: '2024-01-13T08:00:00Z',
    updated_at: '2024-01-20T11:30:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-2',
    clientName: 'Carlos Rodríguez',
    clientEmail: 'carlos.rodriguez@email.com',
    clientPhone: '+1 (555) 234-5678',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '10:00',
    time: '10:00',
    endTime: '11:30',
    userId: 'demo-user',
    createdAt: '2024-01-13T08:00:00Z',
    updatedAt: '2024-01-20T11:30:00Z',
    priority: 'high',
    tags: ['Primera consulta'],
    reminderSent: true
  },
  // Cancelled appointment
  {
    id: 'demo-apt-9',
    business_id: 'demo-business',
    location_id: 'demo-location-1',
    service_id: 'demo-service-2',
    user_id: 'demo-user',
    client_id: 'demo-client-4',
    title: 'Empaste Dental',
    description: 'Empaste programado',
    client_name: 'Juan Martínez',
    client_email: 'juan.martinez@email.com',
    client_phone: '+1 (555) 456-7890',
    client_whatsapp: '+1 (555) 456-7890',
    start_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T09:30:00.000Z'),
    end_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().replace(/T.*/, 'T11:00:00.000Z'),
    status: 'cancelled',
    location: 'Sede Principal - Centro',
    notes: 'Cliente canceló por emergencia, reprogramar',
    price: 120,
    currency: 'EUR',
    reminder_sent: true,
    cancelled_reason: 'Emergencia familiar',
    created_at: '2024-01-16T08:00:00Z',
    updated_at: '2024-01-18T08:00:00Z',
    created_by: 'demo-user',
    
    // Legacy fields for backward compatibility
    clientId: 'demo-client-4',
    clientName: 'Juan Martínez',
    clientEmail: 'juan.martinez@email.com',
    clientPhone: '+1 (555) 456-7890',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    startTime: '09:30',
    time: '09:30',
    endTime: '11:00',
    userId: 'demo-user',
    createdAt: '2024-01-16T08:00:00Z',
    updatedAt: '2024-01-18T08:00:00Z',
    priority: 'medium',
    tags: ['Cancelado'],
    reminderSent: true
  }
]

export async function loadDemoData() {
  try {
    // Store demo data using the same keys as the application expects
  localStorage.setItem('demo-business', JSON.stringify(demoBusiness))
  localStorage.setItem('demo-locations', JSON.stringify(demoLocations))
  localStorage.setItem('demo-services', JSON.stringify(demoServices))
  localStorage.setItem('demo-clients', JSON.stringify(demoClients))
  localStorage.setItem('demo-appointments', JSON.stringify(demoAppointments))
    // Demo data loaded
  } catch {
    // Silent fail in demo mode
  }
}

// Call this function once to initialize demo data
if (typeof window !== 'undefined') {
  loadDemoData()
}